language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - mingw-w64

env:
  global:
    - travis_boost_version=1.71.0
  matrix:
    - configuration=Debug   platform=x86
    - configuration=Release platform=x86
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

before_script:
  - |-
    ./cmake/ci/boost/build_travis.py \
        --                           \
        link=static                  \
        target-os=windows            \
        --user-config="$TRAVIS_BUILD_DIR/cmake/toolchains/boost/mingw-w64-$platform.jam" \
        --with-filesystem            \
        --with-program_options       \
        --with-system

script:
  - |-
    ./cmake/ci/build_travis.py \
        --install "$HOME/install" \
        -- \
        -D "BOOST_ROOT=$HOME/boost_1_71_0" \
        -D "BOOST_LIBRARYDIR=$HOME/boost_1_71_0/stage/$platform/$configuration/lib" \
        -D "CMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw-w64-$platform.cmake" \
        -D CMAKE_SYSTEM_NAME=Windows
