language: cpp
os: linux
dist: bionic

branches:
  only:
    - master

addons:
  apt:
    update: true
    packages:
      - mingw-w64

env:
  global:
    - boost_version=1.71.0
  matrix:
    - build_type=debug   arch=x86
    - build_type=release arch=x86
    - build_type=debug   arch=x64
    - build_type=release arch=x64

before_script:
  - ./.travis/build_boost.sh

script:
  - ./.travis/build.sh
