language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - mingw-w64

env:
  global:
    - boost_version=1.72.0
  jobs:
    - configuration=Debug   platform=x86
    - configuration=Release platform=x86
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

jobs:
  fast_finish: true

before_script:
  - cd cmake
  - >-
    python3 -m project.ci.travis.boost
    --mingw
    --
    --with-filesystem
    --with-program_options
    --with-system

script:
  - >-
    python3 -m project.ci.travis.cmake
    --install "$HOME/install"
    --mingw
