language: cpp
os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - mingw-w64

env:
  global:
    - travis_boost_version=1.71.0
  jobs:
    - configuration=Debug   platform=x86
    - configuration=Release platform=x86
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

jobs:
  fast_finish: true

before_script:
  - >-
    ./cmake/boost/build/ci/travis.py
    --link static
    --
    --user-config="$TRAVIS_BUILD_DIR/cmake/boost/toolchains/mingw-w64-$platform.jam"
    --with-filesystem
    --with-program_options
    --with-system

script:
  - >-
    ./cmake/cmake/build/ci/travis.py
    --install "$HOME/install"
    --
    -D "CMAKE_TOOLCHAIN_FILE=cmake/cmake/toolchains/mingw-w64-$platform.cmake"
    -D "BOOST_ROOT=$HOME/boost_1_71_0"
    -D "BOOST_LIBRARYDIR=$HOME/boost_1_71_0/stage/$platform/$configuration/lib"
