version: '{build}'

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - appveyor_asm: 1
    - appveyor_asm: 0

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  exclude:
    - appveyor_asm: 1
      platform: x64

build_script:
  - ps: .\.appveyor\build.ps1

test_script:
  - ps: .\.appveyor\test.ps1

for:
- matrix:
    only:
      - image: Visual Studio 2015
  environment:
    appveyor_boost_version: 1.62.0

- matrix:
    only:
      - image: Visual Studio 2017
  environment:
    appveyor_boost_version: 1.69.0
