version: '{build}'

branches:
  only:
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      appveyor_boost_version: 1.62.0
      appveyor_asm: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      appveyor_boost_version: 1.62.0
      appveyor_asm: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      appveyor_boost_version: 1.69.0
      appveyor_asm: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      appveyor_boost_version: 1.69.0
      appveyor_asm: 0

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  exclude:
    - appveyor_asm: 1
      platform: x64

build_script:
  - ps: .\.appveyor\build.ps1

test_script:
  - ps: .\.appveyor\test.ps1
